apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: devops-project-back
    namespace: argocd
spec:
    project: default

    source:
        repoURL: https://github.com/mariemeNdoye123/ml-backend.git
        targetRevision: HEAD
        path: manifests
    
    destination:
        server: https://kubernetes.default.svc
        namespace: devops-project-deploy

    syncPolicy:
        syncOptions:
        - CreateNamespace=true

        automated:
            selfHeal: true
            prune: true