apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mariemendoye/ml-backend:latest
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: FLASK_ENV
          ports:
            - containerPort: 5000
