apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devops-project
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002
  selector:
    app: backend
